- hosts: all
  
  tasks:
    - name: log into docker hub registry
      docker_login:
        email: "akshaymohan340@gmail.com"
        username: "akshaymohan340"
        password: "MONday@123"

    - name: ensure a container is running
      docker_container:
        name: my_container
        state: started
        image: "akshaymohan340/application:895374bb"
        pull: true
        ports:
          - "5000:5000"